### ISSUE TITLE
[feature request] Add an option to use arch-efiboot to generate efistub for boot from UEFI directly

### ISSUE THREAD

**Issue by mxj4** [archcraft-os/core-packages#1]
By using https://github.com/RobertCsordas/arch-efiboot we can generate new efistub after every kernel update. If you are interested I can create a PR to add this as the third bootloader option.

**Comment by adi1090x** [comment]
Probably too late for that now, aren't we?

**Comment by mxj4** [comment]
yes it's now supported by upstream.
